controller_list:
  - name: fake_arm_group_controller
    joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_wrist_flex_joint
  - name: fake_gripper_group_controller
    joints:
      - gripper_joint